"""
refresh_extensions_feed.py

Refreshes the reference snapshot of the public Nexus v3 /vortex/extensions feed in
resources/: overwrites vortex-extensions-feed.json with the live response and rewrites
the generated tables in vortex-extensions-feed.md (the block between its
feed-snapshot markers). Everything else in that .md, including the "Observations"
section, is hand-written - re-check it after a refresh.

Usage:
    python refresh_extensions_feed.py             # fetch, write the JSON, rewrite the tables
    python refresh_extensions_feed.py --dry-run   # fetch and print the tables, write nothing

Requirements:
    Python standard library only. The endpoint needs no API key.

Reads:
    %APPDATA%\\Vortex\\temp\\nexus_gamelist.json   (only for the game-folder coverage row;
                                                   the row reads "unavailable" without it)
"""

import argparse
import datetime
import json
import os
import re
import sys
import urllib.request
from collections import Counter

from vortex_utils import (
    NEXUS_USER_AGENT, REPO_ROOT, CB1_NEXUS_USER_ID,
    list_game_ids, load_vortex_manifest,
)

FEED_URL = "https://api.nexusmods.com/v3/vortex/extensions"
JSON_PATH = os.path.join(REPO_ROOT, "resources", "vortex-extensions-feed.json")
MD_PATH = os.path.join(REPO_ROOT, "resources", "vortex-extensions-feed.md")
MARKER_START = "<!-- feed-snapshot:start (generated by refresh_extensions_feed.py, do not hand-edit) -->"
MARKER_END = "<!-- feed-snapshot:end -->"
BLOCK_RE = re.compile(re.escape(MARKER_START) + r".*?" + re.escape(MARKER_END), re.DOTALL)


def fetch_feed():
    """Return the parsed feed response. Raises on a network error or an unexpected shape."""
    req = urllib.request.Request(FEED_URL, headers={"Accept": "application/json", "User-Agent": NEXUS_USER_AGENT})
    with urllib.request.urlopen(req, timeout=60) as resp:
        payload = json.loads(resp.read())
    data = payload["data"]
    for key in ("extensions", "themes", "translations"):
        if not isinstance(data[key], list):
            raise ValueError(f"data.{key} is not a list")
    return payload


def table(headers, rows):
    """Render a markdown table with padded columns."""
    widths = [max(len(str(r[i])) for r in [headers] + rows) for i in range(len(headers))]

    def line(cells):
        return "| " + " | ".join(str(c).ljust(w) for c, w in zip(cells, widths)) + " |"

    return "\n".join([line(headers), "| " + " | ".join("-" * w for w in widths) + " |"] + [line(r) for r in rows])


def folder_coverage(extensions):
    """Return ("N of M" or an unavailable note, [game-* ids with no ChemBoy1 game row])."""
    rows = load_vortex_manifest(extensions)  # {domain: mod_id}, ChemBoy1 game rows only
    folders = list_game_ids()
    if not rows:
        return "unavailable (needs Vortex's nexus_gamelist.json)", []
    missing = [g for g in folders if g not in rows]
    return f"{len(folders) - len(missing)} of {len(folders)}", missing


def build_block(payload, fetched, size, coverage):
    """Return the generated marker block (both tables) as text."""
    data = payload["data"]
    ext = data["extensions"]
    cb1 = [e for e in ext if e["author_user_id"] == CB1_NEXUS_USER_ID]

    def count(rows, kind):
        return sum(1 for e in rows if e["type"] == kind)

    uploads = sorted(e["uploaded_at"] for e in ext)
    game_ids = {e["game_id"] for e in ext if e.get("game_id")}
    n_game = count(ext, "game")
    ids_note = "one extension per game, see below" if len(game_ids) == n_game else f"NOT one per game, {n_game} game rows"
    authors = Counter((e["author_name"], e["author_user_id"]) for e in ext)
    top = ", ".join(f"{name} {n}" for (name, _), n in authors.most_common(5))

    snapshot = table(["Field", "Value"], [
        ["Fetched (UTC)", fetched],
        ["Source", f"`GET {FEED_URL}` (no API key)"],
        ["File", f"`vortex-extensions-feed.json`, {round(size / 1000)} KB, 2-space indent, UTF-8, LF, one trailing newline"],
        ["Newest upload in feed", f"{uploads[-1]} (extensions list)"],
        ["Oldest upload in feed", f"{uploads[0]} (extensions list)"],
    ])
    counts = table(["Item", "Count"], [
        ["Extensions", len(ext)],
        ["Extensions with `type` `game`", n_game],
        ["Extensions with `type` `other`", count(ext, "other")],
        ["Themes", len(data["themes"])],
        ["Translations", len(data["translations"])],
        ["Distinct extension authors", len(authors)],
        ["Distinct `game_id` values", f"{len(game_ids)} ({ids_note})"],
        ["ChemBoy1 extensions", f"{len(cb1)} ({count(cb1, 'game')} `game`, {count(cb1, 'other')} `other`)"],
        ["Largest extension authors by rows", top],
        ["`game-*` folders with a ChemBoy1 `game` row", coverage],
    ])
    return f"{MARKER_START}\n\n{snapshot}\n\n{counts}\n\n{MARKER_END}"


def rewrite_markdown(block):
    """Return (new_text, eol) with the marker block replaced. Raises if the markers are missing."""
    with open(MD_PATH, "rb") as f:
        raw = f.read()
    eol = "\r\n" if b"\r\n" in raw else "\n"
    text = raw.decode("utf-8").replace("\r\n", "\n")
    if not BLOCK_RE.search(text):
        raise ValueError(f"feed-snapshot markers not found in {MD_PATH}")
    return BLOCK_RE.sub(lambda _: block, text, count=1), eol


def main():
    ap = argparse.ArgumentParser(description="Refresh the Nexus v3 /vortex/extensions reference snapshot in resources/.")
    ap.add_argument("--dry-run", action="store_true", help="fetch and print the generated tables, write nothing")
    args = ap.parse_args()

    try:
        payload = fetch_feed()
    except Exception as ex:
        print(f"ERROR: could not fetch {FEED_URL}: {ex}")
        return 1

    body = json.dumps(payload, indent=2, ensure_ascii=False) + "\n"
    fetched = datetime.datetime.now(datetime.timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    coverage, missing = folder_coverage(payload["data"]["extensions"])
    block = build_block(payload, fetched, len(body.encode("utf-8")), coverage)

    try:
        new_text, eol = rewrite_markdown(block)
    except Exception as ex:
        print(f"ERROR: {ex}")
        return 1

    if args.dry_run:
        print(block)
        print(f"\n[DRY RUN] Would write {JSON_PATH} and update the tables in {MD_PATH}")
    else:
        tmp = JSON_PATH + ".tmp"
        with open(tmp, "w", encoding="utf-8", newline="\n") as f:
            f.write(body)
        os.replace(tmp, JSON_PATH)
        with open(MD_PATH, "w", encoding="utf-8", newline="") as f:
            f.write(new_text.replace("\n", eol))
        print(f"Wrote {JSON_PATH}")
        print(f"Updated the tables in {MD_PATH}")

    if missing:
        print(f"\ngame-* folders with no ChemBoy1 game row ({len(missing)}): {', '.join(missing)}")
    print("Re-check the hand-written 'Observations' section in the .md against the figures above.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
